site_name: General Transit Feed Specification
site_url: https://gtfs.org
repo_url: https://github.com/google/transit

theme:
  logo_light_mode: assets/org-white.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
  name: material
  favicon: assets/org-black.svg
  font:
    text: SF Pro
    code: SF Mono
  features:
     - navigation.tabs
     - navigation.indexes
     - navigation.top
     - toc.integrate
  custom_dir: theme_overrides
extra_css:
  - assets/stylesheets/extra.css
extra:
  analytics:
    provider: google
    property: G-DRBTC7SSDT
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MobilityData
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/mobilitydata
    - icon: fontawesome/brands/slack
      link: https://bit.ly/mobilitydata-slack

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences

plugins:
  - search
  - redirects:
      redirect_maps:
        'gtfs-background.md': 'background.md'
        'reference/static.md': 'schedule/reference.md'
        'reference/realtime/v2.md': 'realtime/reference.md'
        'reference/realtime/v1.md': 'realtime/reference.md'
        'reference/realtime/index.md': 'realtime/reference.md'
        'getting-started.md': 'schedule/index.md'
        'examples.md': 'schedule/examples/index.md'
        'testing.md': 'resources/gtfs.md'
        'best-practices.md': 'schedule/best-practices.md'
        'data-examples.md': 'schedule/data-examples.md'
        'changes.md': 'extensions.md'
        'reference/realtime/changes.md': 'realtime/changes/index.md'
        'reference/static/changes.md': 'schedule/changes/index.md'
        'applications.md': 'resources/apps.md'
        'license.md': 'about.md'
        'realtime/service-alerts.md': 'realtime/feed-entities/service-alerts.md'
        'realtime/trip-updates.md': 'realtime/feed-entities/trip-updates.md'
        'realtime/vehicle-positions.md': 'realtime/feed-entities/vehicle-positions.md'
        'realtime/code-examples/index.md': 'realtime/language-bindings/index.md'
        'realtime/code-examples/dotnet.md': 'realtime/language-bindings/dotnet.md'
        'realtime/code-examples/java.md': 'realtime/language-bindings/java.md'
        'realtime/code-examples/nodejs.md': 'realtime/language-bindings/nodejs.md'
        'realtime/code-examples/python.md': 'realtime/language-bindings/python.md'
        'realtime/code-examples/golang.md': 'realtime/language-bindings/golang.md'
        'realtime/code-examples/ruby.md': 'realtime/language-bindings/ruby.md'
        'realtime/code-examples/php.md': 'realtime/language-bindings/php.md'
  - mkdocs-simple-hooks:
      hooks:
        on_config: "hooks.on_config:deploy_hooks"
nav:
- Home: index.md
- GTFS Schedule:
  - Getting Started: schedule/index.md
  - Reference: schedule/reference.md
  - Best Practices: schedule/best-practices.md
  - Examples:
    - schedule/examples/index.md
    - Example GTFS Feed: schedule/example-feed.md
    - Data Examples: schedule/data-examples.md
  - Changes:
    - schedule/changes/index.md
    - Specification Amendment Process: schedule/process.md
    - Guiding Principles: schedule/guiding-principles.md
    - Revision History: schedule/revision-history.md
- GTFS Realtime: 
  - Getting Started: realtime/index.md
  - Reference: realtime/reference.md
  - Protobuf: realtime/proto.md
  - Best Practices: realtime/best-practices.md
  - Feed Entities:
    - realtime/feed-entities/index.md
    - Trip Updates: realtime/feed-entities/trip-updates.md
    - Service Alerts: realtime/feed-entities/service-alerts.md
    - Vehicle Positions: realtime/feed-entities/vehicle-positions.md
  - Feed Examples:
    - realtime/feed-examples/index.md
    - Trip Updates: realtime/feed-examples/trip-updates.md
    - Service Alerts: realtime/feed-examples/service-alerts.md
  - Language Bindings: 
    - realtime/language-bindings/index.md
    - .NET: realtime/language-bindings/dotnet.md
    - Java: realtime/language-bindings/java.md
    - JavaScript/Node.js: realtime/language-bindings/nodejs.md
    - Python: realtime/language-bindings/python.md
    - Golang: realtime/language-bindings/golang.md
    - Ruby: realtime/language-bindings/ruby.md
    - PHP: realtime/language-bindings/php.md
  - Changes:
    - realtime/changes/index.md
    - Specification Amendment Process: realtime/process.md
    - Guiding Principles: realtime/guiding-principles.md
    - Revision History: realtime/revision-history.md
    - Realtime Extensions: realtime/extensions.md
- Resources:
  - resources/index.md
  - resources/getting-started.md
  - resources/community.md
  - resources/data.md
  - resources/software-for-creating-apis.md
  - resources/agency-tools.md
  - resources/hardware.md
  - resources/apps.md
  - resources/sdk.md
  - resources/visualizations.md
  - resources/gtfs.md
  - resources/gtfs-realtime.md
  - resources/siri.md
  - resources/multimodal.md
  - resources/other.md
- Extensions: extensions.md
- About: about.md
