name: build and deploy v2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install \
               mkdocs \
               mkdocs-material \
               mkdocs-static-i18n \
               mkdocs-redirects
      - run: |
          mkdocs build
          swift scripts/fixSearchIndex.swift
