name: build
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
        env:
          MKDOCS_TOKEN: ${{ secrets.MKDOCS_TOKEN }}
      - run: pip install -r requirements.txt
      - run: pip install git+https://$MKDOCS_TOKEN@github.com/squidfunk/mkdocs-material-insiders.git==4.21.0
      - run: mkdocs gh-deploy --force --clean --verbose
