name: Build and deploy the GTFS documentation
on:
  push:
    branches: [main]
jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository 
      uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Build the website
      run: |
        mkdocs build
        swift scripts/fixSearchIndex.swift
        git config --global --add safe.directory /github/workspace
    - name: Force push to destination branch
      uses: ad-m/github-push-action@v0.5.0
      with:
        # Token for the repo
        # Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Destination branch to push changes
        branch: gh-pages-test
        # Use force push to fully overwrite the destination branch
        force: true
